<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\Content.Tests\</OutputPath>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <Import Project="../MSBuild/Content.props" />
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <Import Project="..\RobustToolbox\Imports\Shared.props" />
  <ItemGroup>
    <ProjectReference Include="..\Content.Client\Content.Client.csproj" />
    <ProjectReference Include="..\Content.Packaging\Content.Packaging.csproj" />
    <ProjectReference Include="..\Content.Shared\Content.Shared.csproj" />
  </ItemGroup>

  <Import Project="..\RobustToolbox\MSBuild\Robust.Properties.targets" />
</Project>
